export const menuItems = {
    items: [
        {name: 'Taco Bute',
        descripcion: 'Un taco embutinado, con vegetales buti, y pimienta buti.',
        },
        {name: 'Sushi Bute',
        descripcion: 'Sushi de berenjenas con chorizo, creados en casa por el masterchef Buti.',
        },
        {name: 'Pollo a la Buti',
        descripcion: 'El pollo mas exquisito recien sacado de Londres. Recomendacion de El Chef Buti y Remi de Ratatouille',
        },
        {name: 'Buti',
        descripcion: 'Ehhhh qsy lo hizo el buteee!!!',
        },
        {name: 'Un perro',
        descripcion: 'Ehhhh qsy lo hizo el buteee!!!',
        },
        {name: 'Una de 14',
        descripcion: 'Ehhhh qsy lo hizo el buteee!!!',
        },
        {name: 'Un GATO',
        descripcion: 'Ehhhh qsy lo hizo el buteee!!!',
        },
    ]
}
